name: Daily News Fetch

on:
  schedule:
    # 매일 00:10 KST (UTC 15:10)
    - cron: '10 15 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser

      - name: Fetch news
        run: |
          python scripts/fetch_news.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: daily update" || echo "nothing to commit"
          git push
