name: Daily News Fetch

on:
  workflow_dispatch:
    inputs:
      start:
        description: '시작일 (YYYY-MM-DD, KST 기준)'
        required: true
      end:
        description: '종료일 (YYYY-MM-DD, KST 기준)'
        required: true

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Fetch news (Naver)
        env:
          START: ${{ inputs.start }}
          END: ${{ inputs.end }}
        run: |
          python scripts/fetch_news.py

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "fetch: ${{ inputs.start }}~${{ inputs.end }} (KST)" || echo "nothing to commit"
          git push
